export const colors = {
  white: "#fff",
  tabBarbutton: "skyblue",
  buttonBackground: "skyblue",
  buttonTextColor: "#fff",
  gray: "#808080",
  modalOverlay: "rgba(0, 0, 0, 0.5)",
  transparentGray: "rgba(128, 128, 128, 0.5)",
  profilePressableBackground: "#f9f9f9",
  profilePressableFeedback: "#e0e0e0",
  buttonPressedBackground: "lightblue",
};

export const textSizes = {
  small: 12,
  medium: 16,
  large: 20,
};

// this is copied from Postman, which gets from the external API (not free!)
// this won't change often, hardcoding makes less API calls and app works faster
export const currencies = [
  { value: "ANG", label: "ANG - Netherlands Antillean Guilder" },
  { value: "SVC", label: "SVC - Salvadoran Colón" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "XCD", label: "XCD - East Caribbean Dollar" },
  { value: "MVR", label: "MVR - Maldivian Rufiyaa" },
  { value: "HRK", label: "HRK - Croatian Kuna" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "MWK", label: "MWK - Malawian Kwacha" },
  { value: "XAG", label: "XAG - Silver (troy ounce)" },
  { value: "MAD", label: "MAD - Moroccan Dirham" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "NAD", label: "NAD - Namibian Dollar" },
  { value: "GNF", label: "GNF - Guinean Franc" },
  { value: "KES", label: "KES - Kenyan Shilling" },
  { value: "MZN", label: "MZN - Mozambican Metical" },
  { value: "BTN", label: "BTN - Bhutanese Ngultrum" },
  { value: "MGA", label: "MGA - Malagasy Ariary" },
  { value: "AZN", label: "AZN - Azerbaijani Manat" },
  { value: "XAU", label: "XAU - Gold (troy ounce)" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "EGP", label: "EGP - Egyptian Pound" },
  { value: "BSD", label: "BSD - Bahamian Dollar" },
  { value: "TWD", label: "TWD - New Taiwan Dollar" },
  { value: "GGP", label: "GGP - Guernsey Pound" },
  { value: "LVL", label: "LVL - Latvian Lats" },
  { value: "MMK", label: "MMK - Myanma Kyat" },
  { value: "WST", label: "WST - Samoan Tala" },
  { value: "ILS", label: "ILS - Israeli New Sheqel" },
  { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "GBP", label: "GBP - British Pound Sterling" },
  { value: "TZS", label: "TZS - Tanzanian Shilling" },
  { value: "SDG", label: "SDG - South Sudanese Pound" },
  { value: "LAK", label: "LAK - Laotian Kip" },
  { value: "DJF", label: "DJF - Djiboutian Franc" },
  { value: "BYN", label: "BYN - New Belarusian Ruble" },
  { value: "LBP", label: "LBP - Lebanese Pound" },
  { value: "RWF", label: "RWF - Rwandan Franc" },
  { value: "PEN", label: "PEN - Peruvian Nuevo Sol" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "ZMK", label: "ZMK - Zambian Kwacha (pre-2013)" },
  { value: "RSD", label: "RSD - Serbian Dinar" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "MUR", label: "MUR - Mauritian Rupee" },
  { value: "BWP", label: "BWP - Botswanan Pula" },
  { value: "GEL", label: "GEL - Georgian Lari" },
  { value: "KMF", label: "KMF - Comorian Franc" },
  { value: "UZS", label: "UZS - Uzbekistan Som" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "CUC", label: "CUC - Cuban Convertible Peso" },
  { value: "BGN", label: "BGN - Bulgarian Lev" },
  { value: "JOD", label: "JOD - Jordanian Dinar" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "BDT", label: "BDT - Bangladeshi Taka" },
  { value: "PKR", label: "PKR - Pakistani Rupee" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "KZT", label: "KZT - Kazakhstani Tenge" },
  { value: "CVE", label: "CVE - Cape Verdean Escudo" },
  { value: "HNL", label: "HNL - Honduran Lempira" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },
  { value: "ERN", label: "ERN - Eritrean Nakfa" },
  { value: "NPR", label: "NPR - Nepalese Rupee" },
  { value: "ZMW", label: "ZMW - Zambian Kwacha" },
  { value: "FKP", label: "FKP - Falkland Islands Pound" },
  { value: "DZD", label: "DZD - Algerian Dinar" },
  { value: "JMD", label: "JMD - Jamaican Dollar" },
  { value: "CRC", label: "CRC - Costa Rican Colón" },
  { value: "GMD", label: "GMD - Gambian Dalasi" },
  { value: "PLN", label: "PLN - Polish Zloty" },
  { value: "AMD", label: "AMD - Armenian Dram" },
  { value: "BMD", label: "BMD - Bermudan Dollar" },
  { value: "BZD", label: "BZD - Belize Dollar" },
  { value: "BBD", label: "BBD - Barbadian Dollar" },
  { value: "SBD", label: "SBD - Solomon Islands Dollar" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "ALL", label: "ALL - Albanian Lek" },
  { value: "IQD", label: "IQD - Iraqi Dinar" },
  { value: "BIF", label: "BIF - Burundian Franc" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "GIP", label: "GIP - Gibraltar Pound" },
  { value: "BAM", label: "BAM - Bosnia-Herzegovina Convertible Mark" },
  { value: "LKR", label: "LKR - Sri Lankan Rupee" },
  { value: "QAR", label: "QAR - Qatari Rial" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "TOP", label: "TOP - Tongan Paʻanga" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "ZAR", label: "ZAR - South African Rand" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "BYR", label: "BYR - Belarusian Ruble" },
  { value: "KPW", label: "KPW - North Korean Won" },
  { value: "CZK", label: "CZK - Czech Republic Koruna" },
  { value: "STD", label: "STD - São Tomé and Príncipe Dobra" },
  { value: "BTC", label: "BTC - Bitcoin" },
  { value: "ZWL", label: "ZWL - Zimbabwean Dollar" },
  { value: "LSL", label: "LSL - Lesotho Loti" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "PAB", label: "PAB - Panamanian Balboa" },
  { value: "IRR", label: "IRR - Iranian Rial" },
  { value: "CNH", label: "CNH - Chinese Yuan Offshore" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "XPF", label: "XPF - CFP Franc" },
  { value: "XOF", label: "XOF - CFA Franc BCEAO" },
  { value: "XDR", label: "XDR - Special Drawing Rights" },
  { value: "OMR", label: "OMR - Omani Rial" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "NIO", label: "NIO - Nicaraguan Córdoba" },
  { value: "AOA", label: "AOA - Angolan Kwanza" },
  { value: "SCR", label: "SCR - Seychellois Rupee" },
  { value: "MOP", label: "MOP - Macanese Pataca" },
  { value: "ISK", label: "ISK - Icelandic Króna" },
  { value: "VND", label: "VND - Vietnamese Dong" },
  { value: "VES", label: "VES - Sovereign Bolivar" },
  { value: "USD", label: "USD - United States Dollar" },
  { value: "UYU", label: "UYU - Uruguayan Peso" },
  { value: "VEF", label: "VEF - Venezuelan Bolívar Fuerte" },
  { value: "MRU", label: "MRU - Mauritanian Ouguiya" },
  { value: "UGX", label: "UGX - Ugandan Shilling" },
  { value: "DOP", label: "DOP - Dominican Peso" },
  { value: "UAH", label: "UAH - Ukrainian Hryvnia" },
  { value: "BOB", label: "BOB - Bolivian Boliviano" },
  { value: "TTD", label: "TTD - Trinidad and Tobago Dollar" },
  { value: "KGS", label: "KGS - Kyrgystani Som" },
  { value: "TND", label: "TND - Tunisian Dinar" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "TMT", label: "TMT - Turkmenistani Manat" },
  { value: "GHS", label: "GHS - Ghanaian Cedi" },
  { value: "TJS", label: "TJS - Tajikistani Somoni" },
  { value: "KHR", label: "KHR - Cambodian Riel" },
  { value: "ETB", label: "ETB - Ethiopian Birr" },
  { value: "PGK", label: "PGK - Papua New Guinean Kina" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "AED", label: "AED - United Arab Emirates Dirham" },
  { value: "GTQ", label: "GTQ - Guatemalan Quetzal" },
  { value: "LRD", label: "LRD - Liberian Dollar" },
  { value: "SYP", label: "SYP - Syrian Pound" },
  { value: "KYD", label: "KYD - Cayman Islands Dollar" },
  { value: "SRD", label: "SRD - Surinamese Dollar" },
  { value: "HTG", label: "HTG - Haitian Gourde" },
  { value: "LYD", label: "LYD - Libyan Dinar" },
  { value: "SLL", label: "SLL - Sierra Leonean Leone" },
  { value: "SLE", label: "SLE - Sierra Leonean Leone" },
  { value: "SHP", label: "SHP - Saint Helena Pound" },
  { value: "IMP", label: "IMP - Manx pound" },
  { value: "FJD", label: "FJD - Fijian Dollar" },
  { value: "PYG", label: "PYG - Paraguayan Guarani" },
  { value: "KRW", label: "KRW - South Korean Won" },
  { value: "SZL", label: "SZL - Swazi Lilangeni" },
  { value: "GYD", label: "GYD - Guyanaese Dollar" },
  { value: "MDL", label: "MDL - Moldovan Leu" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "LTL", label: "LTL - Lithuanian Litas" },
  { value: "SOS", label: "SOS - Somali Shilling" },
  { value: "MNT", label: "MNT - Mongolian Tugrik" },
  { value: "AFN", label: "AFN - Afghan Afghani" },
  { value: "CUP", label: "CUP - Cuban Peso" },
  { value: "CLF", label: "CLF - Chilean Unit of Account (UF)" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "TRY", label: "TRY - Turkish Lira" },
  { value: "YER", label: "YER - Yemeni Rial" },
  { value: "HUF", label: "HUF - Hungarian Forint" },
  { value: "BND", label: "BND - Brunei Dollar" },
  { value: "JEP", label: "JEP - Jersey Pound" },
  { value: "MKD", label: "MKD - Macedonian Denar" },
  { value: "AWG", label: "AWG - Aruban Florin" },
  { value: "CDF", label: "CDF - Congolese Franc" },
  { value: "VUV", label: "VUV - Vanuatu Vatu" },
  { value: "XAF", label: "XAF - CFA Franc BEAC" },
  { value: "KWD", label: "KWD - Kuwaiti Dinar" },
  { value: "DKK", label: "DKK - Danish Krone" },
];
